### PR TITLE
fix: Resolving TS issues by adding @babel/preset-typescript

### PR DESCRIPTION
**Pull request by rschristian**
Would resolve issue described at #4.

### CODE REVIEW

**Comment by marvinhagemeister** [comment]
Awesome, thank you so much for the PR :tada: Let's add a simple test case so that we can be sure not to regress on this in the future :+1: Adding a simple TS test file with a simple jsx test should do the job.

**Comment by rschristian** [comment]
Sorry, completely blanked on adding tests. 

I added a dead-simple test by typing a component. Should do the trick and cover the (simple) bases, hopefully this was what you had in mind?

**Review by marvinhagemeister — APPROVED** [review]
Yup, that's perfect! Again thank you so much for submitting a fix for this 🙌 💯

**Comment by marvinhagemeister** [comment]
I've just released v4.0.2 which includes your PR :tada:

**Comment by rschristian** [comment]
Great, thanks for letting me know!

If you have a moment at some point [I opened up a PR in the TS template repo to integrate this fix](https://github.com/preactjs-templates/typescript/pull/40). Just bumps the versions of this library and Jest, to fulfill peer dependencies/suppress a warning.

**Pull request merged**
